//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMusicBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusicStudioBaseEntities : DbContext
    {
        private static MusicStudioBaseEntities _context;
        public static MusicStudioBaseEntities GetContext()
        {
            if (_context == null)
                _context = new MusicStudioBaseEntities();
            return _context;
        }

        public MusicStudioBaseEntities()
            : base("name=MusicStudioBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Alboms> Alboms { get; set; }
        public virtual DbSet<Instruments> Instruments { get; set; }
        public virtual DbSet<MusicStudios> MusicStudios { get; set; }
        public virtual DbSet<Producers> Producers { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Singers> Singers { get; set; }
        public virtual DbSet<Tirage> Tirage { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
    }
}
