//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMusicBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int idOrder { get; set; }
        public string NameOrder { get; set; }
        public string NameSinger { get; set; }
        public string FamiliaSinger { get; set; }
        public string PatronymicSinger { get; set; }
        public string Instrument { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<int> CountCompositions { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    }
}
